### ISSUE TITLE
Uglify on the browser

### ISSUE THREAD

**Issue by DrummerHead** [ForbesLindesay/uglify-to-browserify#3]
Hi! I'm trying to use uglify on the browser. It would ideal to be able to pass a string and an options object to uglify and then get back another string, completely client side.

From the title of this repo, I'm guessing I could `import` uglify on my JS, do my thing, and then be able to export it for use on the browser.

Is this project what I am looking for? If so, could I see some example code, ideally in the README?

Thank you for your time!

**Comment by ForbesLindesay** [comment]
This project does not need to be used directly.  It is used automatically when you `require('uglify-js')`.

To use this, simply use uglify-js exactly like you would on the server side, then run your code through browserify.
